# Generated by Django 5.0.7 on 2024-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('ip', models.CharField(max_length=15, null=True)),
                ('hostname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url', models.URLField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
