# Generated by Django 4.2.14 on 2024-10-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0002_alter_vulnerability_category_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='linked_case',
            new_name='linked_target',
        ),
    ]
