# Generated by Django 4.2.14 on 2024-10-26 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0003_rename_linked_case_note_linked_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date(2024, 10, 26)),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
