# Generated by Django 4.2.14 on 2024-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0013_alter_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('Capture the Flag', 'Capture The Flag'), ('In the Wild', 'In The Wild'), ('Bug Bounty', 'Bug Bounty')], default='Wild', max_length=16),
        ),
    ]
