# Generated by Django 4.2.14 on 2024-11-09 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0014_alter_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 11, 9), null=True),
        ),
    ]
