# Generated by Django 5.0.7 on 2024-11-21 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0015_target_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 21)),
        ),
        migrations.AlterField(
            model_name='target',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_update',
            field=models.DateField(default=datetime.date(2024, 11, 21), null=True),
        ),
    ]
