# Generated by Django 4.2.16 on 2025-02-17 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0016_alter_note_date_alter_target_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='operating_system',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Unknown', 'Unknown')], default='Unknown', max_length=7),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.date(2025, 2, 17)),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_update',
            field=models.DateField(default=datetime.date(2025, 2, 17), null=True),
        ),
    ]
